import { Toaster } from '@/components/ui/toaster'
import './global.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Crypto Payment Integration Test',
  description: 'Generated by Manzi-Cedrick Dev',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
      <Toaster/>
    </html>
  )
}
